- name: more about loops
  hosts: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name:'nginx',state:'removed'}
    - { name:'zip',state:'present'}