- name: catalogue-service
  hosts: backend
  become: yes
  vars:
    http_port: 80
  tasks:
  - name: disable existing nodejs module stream
    command: dnf module disable nodejs -y
  - name: enable nodejs:20 module stream 
    command: dnf module enable nodejs:20 -y
  - name: install nodejs
    dnf:
      name: nodejs
      state: installed
