- name: catalogue-service
  hosts: backend
  become: yes
  vars:
    http_port: 80
  tasks:
  - name: disable existing nodejs module stream
    command: dnf module disable nodejs -y
  - name: enable nodejs:20 module stream 
    command: dnf module enable nodejs:20 -y
  - name: install nodejs
    dnf:
      name: nodejs
      state: installed
  - name: create roboshop user
    user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: yes
      comment: "roboshop user created"
  - name: create /app folder
    file:
      path: /app
      state: directory
      mode: '0755'
  - name: download catalogue-v3
    get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip"
      dest: /tmp/catalogue.zip
      mode: '0644'
      
  - name: unzip the catalogue
    command: bash -c "cd /app && unzip /tmp/catalogue.zip && ls -la"

  - name: update the package.json
    command: npm install
  - name: create systemd catalogue service 
    copy:
      dest: /etc/systemd/system/catalogue.service
      content: |
        [Unit]
        Description = Catalogue Service

        [Service]
        User=roboshop
        Environment=MONGO=true
        // highlight-start
        Environment=MONGO_URL="mongodb://mongodb.jsprajampeta.org:27017/catalogue"
        // highlight-end
        ExecStart=/bin/node /app/server.js
        SyslogIdentifier=catalogue

        [Install]
        WantedBy=multi-user.target
    notify: reload systemd

  handlers:
    - name: reload systemd
      service:
        name: catalogue
        state: restarted

  
