- name: catalogue-service
  hosts: backend
  become: yes
  vars:
    http_port: 80
  tasks:
  - name: disable existing nodejs module stream
    dnf:
      name: "@nodejs"
      state: disabled
  - name: enable nodejs:20 module stream 
    dnf:
      name: "@nodejs:20" #@nodejs refers to the module stream, which allows you to enable, disable, or switch between different versions
      state: enabled
  - name: install nodejs
    dnf:
      name: nodejs
      state: installed
