- name: install nginx
  hosts: local
  become: yes
  tasks:
  - name: install nginx when redhat
    debug:
      - name: nginx
        state: installed
    when: ansible_os_family == "RedHat"
  - name: install nginx when debian
    debug:
      name: nginx
      state: installed
    when: ansible_os_family == "Debian"