- name: local-connection
  hosts: local #executes in the same Ansible server.
  connection: local
  vars_files:
  - variables.yaml
  tasks:
  - name: enabling debug
    debug: 
      msg: "enabling the debug"
  - name: enabling ping
    ping:
  - name: printing the variables
    debug:
      msg: "Hello {{ NAME }} and his role {{ ROLE }}"
